auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Steven Wang's Web
url: http://www.wangdingwen.net
feed: /atom.xml
author_info: <a href="http://www.wangdingwen.net/">Steven Wang</a>
